# Generated by Django 4.2.3 on 2023-07-31 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_API', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='unit',
        ),
        migrations.AddField(
            model_name='unit',
            name='unit',
            field=models.ManyToManyField(to='home_API.units'),
        ),
    ]
