# Generated by Django 4.2.3 on 2023-07-31 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_API', '0002_remove_unit_unit_unit_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='unit',
        ),
        migrations.AddField(
            model_name='unit',
            name='unit',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
