# Generated by Django 4.2.3 on 2023-08-03 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_API', '0003_remove_unit_unit_unit_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='Images/None/no0img.jpg', upload_to='Images/')),
            ],
        ),
    ]
