# Generated by Django 4.2.3 on 2023-08-15 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_API', '0005_image_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_API.project'),
        ),
    ]
