# Generated by Django 4.2.3 on 2023-08-15 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_API', '0007_alter_image_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='Images/FloorMap/')),
                ('unit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_API.unit')),
            ],
        ),
    ]
