# Generated by Django 4.2.3 on 2023-08-16 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_API', '0008_floormap'),
    ]

    operations = [
        migrations.RenameField(
            model_name='floormap',
            old_name='unit_id',
            new_name='unit',
        ),
    ]
