# Generated by Django 4.2.3 on 2023-09-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_API', '0009_rename_unit_id_floormap_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
