# Generated by Django 4.2.3 on 2023-07-31 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchfilter',
            name='startBudget',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='searchfilter',
            name='stopBudget',
            field=models.FloatField(),
        ),
    ]
